lenovo/xclarity_client

- docs/apib/aicc.apib
- spec/spec_helper.rb
- spec/xclarity_client_spec.rb
- xclarity_client.gemspec
Using `apib/mock_server` gem to create a mock server based on API
Blueprints files (which are Markdown files to describe an API)
This not only allows us to generate API documentation, but also
locally test our client.
> Added API Blueprints for API test mocking

- lib/xclarity_client/cabinet_management.rb
- lib/xclarity_client/canister_management.rb
- lib/xclarity_client/chassi_management.rb
- lib/xclarity_client/client.rb
- lib/xclarity_client/cmm_management.rb
- lib/xclarity_client/fan_management.rb
- lib/xclarity_client/fan_mux_management.rb
- lib/xclarity_client/node_management.rb
- lib/xclarity_client/power_supply_management.rb
- lib/xclarity_client/scalable_complex_management.rb
- lib/xclarity_client/switch_management.rb
- lib/xclarity_client/xclarity_base.rb
- lib/xclarity_client/xclarity_management_mixin.rb
The XLCA API allows query string parameters. This pull request allows `XClarityClient::XClarityBase::connection` to receive a opts hash that sets query string parameters, thus you can do things like:
```
client = XClarityClient::Client.new...
client.discover_cabinet(status: "includestandalone")
```
> Enables query string settings through options hash

- lib/xclarity_client/configuration.rb
There was a dangerous stdout log in configuration, which could
output user data
> [Bugfix/Critical] Removing dangerous config log

- example/simple.rb
Summary:
Changed the configuration parameter from ssl_verify to verify_ssl
Description:
In commit "Naming env refactoring: from SSL_VERIFY to VERIFY_SSL" done on Oct 25 2016, the configuration parameter was changed. This was not reflected in the example/simple.rb. This commit is done to fix the same,
> Changed the configuration parameter from ssl_verify to verify_ssl

- lib/xclarity_client/xclarity_base.rb
- spec/spec_helper.rb
- spec/xclarity_client_node_spec.rb
This PR is to resolve the issue that requires users to input   the URL of the form https://  when using the client.  This PR will look for https:// or http://  if neither is found it will prepend https:// to the provided hostname or IP address provided.   
This should also remove the requirement in ManageIQ to enter https://<ip> in the hostname field.
@miq_bot assign @walteraa
> Connection url

- lib/xclarity_client/xclarity_resource.rb
This PR is a bug fix to xclarity_resource:
- We had a gsub that treat string, but we received a symbol.
- We don't need this anymore.
> Bug fix in the attribute manipulator

- lib/xclarity_client/xclarity_resource.rb
We will need the gsub removed. LXCA have attributes with "-" instead of "_".
We don't have problem now because the attributes not in use yet.
> Fix the LXCA attributes pattern

- lib/xclarity_client/node_management.rb
- spec/xclarity_client_node_spec.rb
Logic in the power operations was invalid and did not match the call that was being made in the client.rb file.  This PR corrects the logic and adds additional spec tests to verify power requests.
@miq-bot add_label wip
> Fix issues with the power operations in node_management

- docs/apib/node_bmc.apib
- lib/xclarity_client.rb
- lib/xclarity_client/client.rb
- lib/xclarity_client/node_management.rb
- lib/xclarity_client/xclarity_power_management_mixin.rb
- spec/xclarity_client_node_spec.rb
Adds additional power actions for  restart now, power off now,  restart to F1 setup and restart the management controller.
Introduces a PowerManagement mixin to begin modularizing the client class. Moves power_ methods from client.rb to xclarity_power_management_mixin.rb.
> Adds additional power actions

- lib/xclarity_client/xclarity_base.rb
- Fix the auth_type condition for use faraday_cookie_jar.
The problem is:  
- Again the manageiq-lenovo-provider will send the auth_type with the value as token or basic_auth.
reference: [PR 90](https://github.com/ManageIQ/manageiq-providers-lenovo/pull/90)
> Fix the auth_type condition

- docs/apib/discover_request.apib
- lib/xclarity_client.rb
- lib/xclarity_client/client.rb
- lib/xclarity_client/discover_request.rb
- lib/xclarity_client/discover_request_management.rb
- spec/xclarity_client_discover_request_spec.rb
The following new functionalities are added:
a. POST on /discoverRequest to discover the manageable devices.
b. GET on /discoverRequest/jobs/<job_id> to monitor the status of a discovery request.
> Add discover request functionality. 

- lib/xclarity_client/chassi.rb
- Add new attributes to chassis resource appended on LXCA API version 1.4
> Adding new attibutes of chassis entity appended on API version 1.4

- lib/xclarity_client/event.rb
- Add new attributes to events resource appended on LXCA API version 1.4
> Adding new attibutes of event entity appended on API version 1.4

- lib/xclarity_client/switch.rb
- Add new attributes to switches resource appended on LXCA API version 1.4
> Adding new attibutes of switch entity appended on API version 1.4

- lib/xclarity_client/scalable_complex.rb
- lib/xclarity_client/xclarity_management_mixin.rb
- Add new attributes to scalable_complex resource appended on LXCA API version 1.4;
- Refactor the strategy to get list names, for the cases where the list name changed in a new version. Basically it adds the possibility to provide more than one list name and the system will look if some of those names exists on response body.
> Adding new attibutes of scalable_complex entity appended on API version 1.4

- lib/xclarity_client/node.rb
- Add new attibutes of node entity appended on LXCA API version 2.0
> Adding new attibutes of node entity appended on LXCA API version 2.0

- lib/xclarity_client/event.rb
- Add new attibutes of event entity appended on LXCA API version 2.0
> Adding new attibutes of event entity appended on LXCA API version 2.0

- lib/xclarity_client/config_profile.rb
- Add new attibutes of config_profile entity appended on LXCA API version 2.0
> Adding new attibutes of config_profile entity appended on LXCA API version 2.0

- lib/xclarity_client.rb
- lib/xclarity_client/connection/connection.rb
- lib/xclarity_client/services/mixins/endpoint_manager_mixin.rb
- lib/xclarity_client/services/mixins/list_name_interpreter_mixin.rb
- lib/xclarity_client/services/mixins/response_builder_mixin.rb
- lib/xclarity_client/services/xclarity_service.rb
- lib/xclarity_client/xclarity_base.rb
- Add `XClarityClient::Services::XClarityService` to centralize some common operations of the services;
- Create `XClarityClient::Services::ResponseBuilderMixin` and `XClarityClient::Services::ListNameInterpreterMixin` to split some concerns of the `XClarityService`.
__Goal:__
- The main goal is make all services classes extend `XClarityService` centralizing the common operations, just needing to implement on sub classes the specific behaviors;
- Improve the code organization and promote a more cohesive structure.
__Depends on:__
https://github.com/lenovo/xclarity_client/pull/91
https://github.com/lenovo/xclarity_client/pull/94
> [DEPENDS_ON: 91, 94] Creating an Abstract Class for Services to centralize some operations

- lib/xclarity_client.rb
- lib/xclarity_client/client.rb
- lib/xclarity_client/services/aicc_management.rb
- lib/xclarity_client/services/cabinet_management.rb
- lib/xclarity_client/services/canister_management.rb
- lib/xclarity_client/services/chassi_management.rb
- lib/xclarity_client/services/cmm_management.rb
- lib/xclarity_client/services/config_pattern_management.rb
- lib/xclarity_client/services/config_profile_management.rb
- lib/xclarity_client/services/config_target_management.rb
- lib/xclarity_client/services/discover_request_management.rb
- lib/xclarity_client/services/discovery_management.rb
- lib/xclarity_client/services/event_management.rb
- lib/xclarity_client/services/fan_management.rb
- lib/xclarity_client/services/fan_mux_management.rb
- lib/xclarity_client/services/ffdc_management.rb
- lib/xclarity_client/services/job_management.rb
- lib/xclarity_client/services/node_management.rb
- lib/xclarity_client/services/persisted_result_management.rb
- lib/xclarity_client/services/power_supply_management.rb
- lib/xclarity_client/services/scalable_complex_management.rb
- lib/xclarity_client/services/services.rb
- lib/xclarity_client/services/switch_management.rb
- lib/xclarity_client/services/unmanage_request_management.rb
- lib/xclarity_client/services/update_repo_management.rb
- lib/xclarity_client/services/user_management.rb
- Remove the `XClarityClient::Endpoints::XclarityEndpoint` declarations on the methods calls in the `client.rb` file;
- Make all the management classes extend the `XClarityClient::Services::XClarityService` promoting a better reuse of common methods;
- Use the `@connection` to make requests to LXCA.
__Depends on:__
- ~https://github.com/lenovo/xclarity_client/pull/91~ - Merged
- ~https://github.com/lenovo/xclarity_client/pull/94~ - Merged
- ~https://github.com/lenovo/xclarity_client/pull/96~ - Merged
> Using the Abstract Service Class in all Management Classes

- .travis.yml
- Update the version of the Ruby used by Travis;
This version is based on the lower one supported by ManageIQ travis.
> Upgrading travis RVM version

- lib/xclarity_client/services/xclarity_service.rb
- Change UUID validation to only check if it is empty or not
This change is necessary because, currenltly, not all of UUIDs in XClarity Client are following the UUID format. Besides, the LXCA REST API response handling is role of the user.
Depends on:
- [Lenovo/xclarity_client#114](https://github.com/lenovo/xclarity_client/pull/114)
> Fixing UUID validation

- lib/xclarity_client/mixins/node_mixin.rb
__This PR is able to__
- Add Location LED name param for node LED actions;
Once that the Location LED name can vary for each node, the name is needed when try to perform such actions.
To provide compatibility with the gem clients, the default value was kept.
> Adding param for LED name on node LED actions

- docs/apib/storages.apib
- lib/xclarity_client/endpoints/storage.rb
- spec/xclarity_client_storage_spec.rb
- Add an enclosure to Storage endpoint in order to enable get its data (like drivers, canisters, etc.)
> Add enclosure to Storage endpoint

- lib/xclarity_client/endpoints/buildable_resource_mixin.rb
Using the `lxca_log` instead of gem client log
> Fixing log

- lib/xclarity_client/connection/connection.rb
- lib/xclarity_client/services/compliance_policy_management.rb
- lib/xclarity_client/services/xclarity_service.rb
- spec/xclarity_client_compliance_policy_spec.rb
- spec/xclarity_client_config_profile_spec.rb
- spec/xclarity_client_discover_request_spec.rb
- spec/xclarity_client_update_repo_spec.rb
- xclarity_client.gemspec
- Add support to passing headers in each connection request of Xclarity Client
- Change Faraday adaptor to use HTTPClient
- Fix problems with Compliance Policy Management (required due to the changes made on the GET requests)
> Add support to request headers to XClarity connection

- docs/apib/storages.apib
- lib/xclarity_client/endpoints/storage.rb
- Fix `/storage` endpoint
- Add Canisters to `/storage` in order to get this data if there is no enclosure on Storage
> Fixing Storage endpoint and adding Canisters on it

- xclarity_client.gemspec
[Faraday got updated](https://github.com/lostisland/faraday/pull/1101) and [we over at manageiq](https://github.com/ManageIQ/manageiq/issues/19760) were hoping maybe that you all might be amenable to letting people update so we can support ruby 2.7.
This is a pretty significant change since 0.9 is from January of 2014. 
Specs greened on this, I'd be happy to fix the codeclimate if needed. 
Thanks!
> Update faraday to any version before January of '14
