lib/xclarity_client/version.rb
=> Updated version

lib/xclarity_client/configuration.rb, lib/xclarity_client/node_management.rb, lib/xclarity_client/virtual_appliance_management.rb, lib/xclarity_client/xclarity_management_mixin.rb
Now log is being used in the follow places:
├── lib
│   ├── xclarity_client
│   │   ├── configuration.rb
│   │   ├── node_management.rb
│   │   ├── node.rb
│   │   ├── virtual_appliance_management.rb
│   │   ├── xclarity_base.rb
│   │   ├── xclarity_management_mixin.rb
Depends on https://github.com/lenovo/xclarity_client/pull/28
=> Add logs in new places

.gitignore
This PR add the logs folder to gitignore.
=> Adding logs to gitignore

lib/xclarity_client/fan_mux.rb, lib/xclarity_client/node.rb, lib/xclarity_client/power_supply.rb, lib/xclarity_client/xclarity_resource.rb
This PR contains: 
- The entities Fan Mux, Nosdes and Power Supply updated to support the LXCA Ruby Client.
=> Update version lxca rest api

lib/xclarity_client/version.rb, xclarity_client.gemspec
=> Publish 0.5.1

lib/xclarity_client/configuration.rb, lib/xclarity_client/xclarity_base.rb, spec/xclarity_client_base_spec.rb, xclarity_client.gemspec
This PR is able to :
* Create a connection between client and LXCA' API  using token authentication.
* Remove variables that are not being used.
=> Fix connection with token and code clear

lib/xclarity_client/version.rb
Change the version number from 0.5.4 to 0.5.5 to push a new version of this gem onto rubygems.org
=> Change the version number from 0.5.4 to 0.5.5

lib/xclarity_client/version.rb
Change the version number to 0.5.7 to push a new version of this gem onto rubygems.org
=> Change version number to 0.5.7

docs/apib/discovery.apib, lib/xclarity_client.rb, lib/xclarity_client/client.rb, lib/xclarity_client/discovery.rb, lib/xclarity_client/discovery_management.rb, spec/xclarity_client_discovery_spec.rb
Add GET functionality on /discovery endpoint to retrieve a list of devices discovered by SLP discovery.
=> Add discovery functionality

lib/xclarity_client/node.rb
- Add new attributes to nodes resource appended on LXCA API version 1.4
=> Adding new attibutes of node entity appended on API version 1.4

lib/xclarity_client/job.rb
- Add new attributes to jobs resource appended on LXCA API version 1.4
=> Adding new attibutes of jobs entity appended on API version 1.4

docs/apib/users.apib, lib/xclarity_client/client.rb, lib/xclarity_client/user.rb, lib/xclarity_client/user_management.rb, spec/xclarity_client_users_spec.rb
**This PR adds:**
* Change user password feature.
**This PR removes:**
* Trailing white spaces on: 
- [client.rb](https://github.com/lenovo/xclarity_client/compare/master...douglasgabriel:chg_pass?expand=1#diff-0a23efd78d85f242122e3a8b54d5ab18)
- [user.rb](https://github.com/lenovo/xclarity_client/pull/81/files#diff-eb0c266123fb18e6007c4f00d68e01cf)
=> Implementing change of user password feature

lib/xclarity_client/connection/connection.rb
- Add the class `XClarityClient::Connection` to handle the LXCA connection setup and interactions.
__Goal:__
The main goal of this approach is to improve the code organization and promote a more cohesive structure
=> Creating XClarityClient::Connection class

.codeclimate.yml, .rubocop_base.yml, .rubocop_cc.yml
- Add some new metrics to codeclimate, based in the ManageIQ projects metrics;
=> Adding new metrics to codeclimate

lib/xclarity_client/schemas.rb, lib/xclarity_client/services/osimage_management.rb
Reducing the lints to improve our codeclimate/rubocop statistics.
Planing to do this on whole project
=> Indenting better few files to reduce our lint issues

docs/apib/squisher.rb
__This PR aims:__
- Fixing codeclimate issues in `docs/apib/squisher.rb`
=> Fixing codeclimate issues in squisher.rb

xclarity_client.gemspec
Updating the faraday gem so it can reach the version 0.13 that is being required by manageiq
=> Update faraday version

docs/apib/chassis.apib, lib/xclarity_client/endpoints/chassi.rb, lib/xclarity_client/mixins/chassi_mixin.rb, lib/xclarity_client/services/chassi_management.rb, spec/xclarity_client_chassi_spec.rb
__This PR is able to__
- Add LED state operations for Chassis;
__Depends on__
~https://github.com/lenovo/xclarity_client/pull/118~ - Merged
=> Adding power LED operations for Chassis

lib/xclarity_client/version.rb
Update version to 0.6.2 prior to publishing new version of the client.
=> update version string to 0.6.2

lib/xclarity_client/endpoints/buildable_resource_mixin.rb
=> Fix bug added on #123

lib/xclarity_client/configuration.rb, lib/xclarity_client/connection/connection.rb
This Pr is able to:
* Add support to define a timeout for `get` requests.
=> Add support to send a get with timeout

lib/xclarity_client/version.rb
I don't have permissions to push to this gem, so this is as good as it's going to get. 
Thanks!
=> version bump for recent faraday update
